#cau hinh moi truong dev
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flascard_db?createDatabaseIfNotExist=true
    username: root
    password:

  flyway:
    enabled: true
    validate-on-migrate: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
