#cau hinh moi truong dev
spring:
  datasource:
    url: ${YOEDU_DB_URL:jdbc:mysql://e4XQFMeuMbogRQK.root:uy5LwcYamnRwU8a1@gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/LeLa?sslMode=VERIFY_IDENTITY}
    username: ${YOEDU_DB_USER:e4XQFMeuMbogRQK.root}
    password: ${YOEDU_DB_PASSWORD:uy5LwcYamnRwU8a1}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
