spring:
  application:
    name: LeLa
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  sql:
    init:
      mode: never
  jwt:
    issuer:
    secret: YOEDU_JWT_SECRET:yoedu-demo-secret-key-12345678901234567890
    access-token-ttl-minutes: 480
    refresh-token-ttl-days: 7
  spring-doc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
      disable-swagger-default-url: true
      operations-sorter: alpha
      tags-sorter: alpha
server:
  port: 8080

